'use client';

import { InlineMath, BlockMath } from 'react-katex';
import { useState } from 'react';
import QuizQuestion from '@/components/QuizQuestion';
import 'katex/dist/katex.min.css';

const quizQuestions = [
  {
    "question": "What is the main function of a transformer in an electrical circuit?",
    "options": [
      "To generate electrical energy",
      "To transfer electrical energy between circuits through induction",
      "To convert electrical energy to heat",
      "To store electrical energy in batteries"
    ],
    "correctAnswer": 1,
    "hint": "Transformers use electromagnetic induction to transfer electrical energy between circuits."
  },
  {
    "question": "What does a step-up transformer do to the voltage levels between circuits?",
    "options": [
      "Increases voltage levels",
      "Decreases voltage levels",
      "Maintains the same voltage levels",
      "Generates random voltage changes"
    ],
    "correctAnswer": 0,
    "hint": "A step-up transformer increases the input voltage to a higher secondary voltage."
  },
  {
    "question": "How is the voltage relationship between the primary and secondary windings determined in a transformer?",
    "options": [
      "By resistance only",
      "By the turns ratio of the coils",
      "By the material of the transformer core",
      "By the frequency of the current"
    ],
    "correctAnswer": 1,
    "hint": "The relationship depends on the ratio of the number of turns between the primary and secondary coils."
  },
  {
    "question": "What is the efficiency formula of a transformer based on output and input power?",
    "options": [
      "\\( \\eta = \\frac{\\text{input power}}{\\text{output power}} \\times 100% \\)",
      "\\( \\eta = \\frac{\\text{output power}}{\\text{input power}} \\times 100% \\)",
      "\\( \\eta = \\text{output power} + \\text{input power} \\)",
      "\\( \\eta = \\frac{\\Delta V}{R} \\times 100% \\)"
    ],
    "correctAnswer": 1,
    "hint": "The efficiency is the ratio of output power to input power, expressed as a percentage."
  },
  {
    "question": "Why do household transformers, like phone chargers, step down voltage levels?",
    "options": [
      "To increase electrical energy supply",
      "To prevent damage to device circuits",
      "To decrease electrical resistance",
      "To stabilize the frequency of electrical currents"
    ],
    "correctAnswer": 1,
    "hint": "Transformers step down voltage in devices like chargers to ensure device protection and functionality."
  }
]

export default function Transformers() {
  const [showQuiz, setShowQuiz] = useState(false);
  const [selectedAnswers, setSelectedAnswers] = useState<(number | null)[]>(new Array(quizQuestions.length).fill(null));
  const [showResults, setShowResults] = useState(false);
  const [score, setScore] = useState(0); 

  const handleAnswerSelect = (questionIndex: number, answerIndex: number) => {
    const newSelectedAnswers = [...selectedAnswers];
    newSelectedAnswers[questionIndex] = answerIndex;
    setSelectedAnswers(newSelectedAnswers);
  };

  const handleSubmit = () => {
    const correctCount = selectedAnswers.reduce((count: number, answer: number | null, index: number) => {
      if (answer === null) return count;
      return count + (answer === quizQuestions[index].correctAnswer ? 1 : 0);
    }, 0);
    setScore(correctCount);
    setShowResults(true);
  };
  return (
    <div className="px-6 sm:px-6 sm:text-xs md:text-base py-6 max-w-4xl mx-auto text-justify">
      <h1 className="text-3xl font-bold mb-6">4.6 Transformers</h1>

      <p>
        A transformer is an electrical device that transfers electrical energy from one circuit to another through the process of electromagnetic induction. It is most commonly used to increase (’step up’) or decrease (’step down’) voltage levels between circuits without altering the frequency. 
      </p>

      <p>
        A step-up transformer converts low primary voltage to high secondary voltage, thereby stepping up the input voltage. In contrast, a step-down transformer decreases the input voltage.
      </p>

      <p>
        A transformer consists of a pair of coils wound on the same core. The core is often shaped as a square loop with the primary and secondary coils wound on opposite sides. The construction allows the magnetic flux generated by a current changing in one coil to induce a current in the neighboring coil.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Operating Principle of Transformers</h2>
      <p>
        The operating principle of a transformer is based on electromagnetic induction. The alternating current (AC) supplied to the primary coil generates a changing magnetic field, which links the primary and secondary coils. This changing magnetic flux induces a current in the secondary coil.
      </p>

      <p>
        Transformers are widely used in power generation grids, the distribution sector, and various electrical devices, including household appliances and industrial equipment. The primary and secondary windings are electrically isolated from each other but are magnetically linked through the common core, allowing electrical power to be transferred between the coils.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Turns Ratio and Voltage Relation</h2>
      <p>
        The voltage difference between the primary and secondary windings is determined by the ratio of turns between the coils. The relationship between the voltage applied to the primary winding (<InlineMath>{'V_p'}</InlineMath>) and the voltage produced on the secondary winding (<InlineMath>{'V_s'}</InlineMath>) is given by:
      </p>
      <div className='overflow-x-auto text-wrap text-xs'>
        <BlockMath>{'\\frac{N_p}{N_s} = \\frac{V_p}{V_s} = \\text{Turns Ratio}'}</BlockMath>
      </div>

      <p>
        Where <InlineMath>{'N_p'}</InlineMath> and <InlineMath>{'N_s'}</InlineMath> are the number of primary and secondary turns, and <InlineMath>{'V_p'}</InlineMath> and <InlineMath>{'V_s'}</InlineMath> are the primary and secondary voltages, respectively.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Efficiency of Transformers</h2>
      <p>
        Transformers can operate with high efficiency, often reaching up to 98%. The efficiency <InlineMath>{'\\eta'}</InlineMath> of a transformer is given by:
      </p>
      <div className='overflow-x-auto text-wrap text-xs'>
        <BlockMath>{'\\eta = \\frac{\\text{output power}}{\\text{input power}} \\times 100%'}</BlockMath>
      </div>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Working Principle of Transformers in Household Appliances</h2>
      <p>
        Alternating current (AC) is typically used to supply power to run household appliances and industrial equipment. Transformers in devices such as phone chargers, laptops, and microwaves are common examples of how transformers step up or step down voltage to suitable levels.
      </p>

      <p>
        For example, in a phone or laptop charger, the voltage from the wall outlet is stepped down to a safe level to charge the device battery. If the voltage were not reduced, it could damage the circuits of the phone or laptop. These electronics are designed to work with low voltages compared to the high voltage supplied by wall outlets.
      </p>

      <p>
        Additionally, a mobile phone charger typically contains a rectifier. After stepping down the voltage, the AC is converted to DC using the rectifier. You will learn about the working principle of rectifiers in Unit 5.
      </p>
      <div className='flex justify-center items-center'>
          <button 
            onClick={() => setShowQuiz(true)}
            className="w-1/2 h-1/2 mt-6 bg-slate-400 hover:bg-slate-500 dark:bg-blue-600 dark:hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition-colors"
          >
            Take Quiz
          </button>
        </div>

      {showQuiz && (
        <div className="fixed inset-0 bg-gray-600 dark:bg-gray-900 bg-opacity-50 dark:bg-opacity-70 flex justify-center items-center z-50">
          <div className="bg-white dark:bg-[#242424] p-8 rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto relative">
            <button 
              onClick={() => {
                setShowQuiz(false);
                setShowResults(false);
                setSelectedAnswers(new Array(quizQuestions.length).fill(null));
              }}
              className="absolute top-4 right-4 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            
            <h2 className="text-2xl font-bold mb-6 dark:text-white">Projectile Motion Quiz</h2>
            <div className="space-y-6">
              {quizQuestions.map((q, index) => (
                <QuizQuestion
                  key={index}
                  question={q.question}
                  options={q.options}
                  correctAnswer={q.correctAnswer}
                  hint={q.hint}
                  selectedAnswer={selectedAnswers[index]}
                  showResults={showResults}
                  onSelectAnswer={(answerIndex) => handleAnswerSelect(index, answerIndex)}
                />
              ))}
            </div>
            <div className="mt-6 flex justify-between">
              {!showResults && (
                <button 
                  onClick={handleSubmit}
                  className="bg-green-500 hover:bg-green-700 dark:bg-green-600 dark:hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition-colors"
                >
                  Submit
                </button>
              )}
              <button 
                onClick={() => {
                  setShowQuiz(false);
                  setShowResults(false);
                  setSelectedAnswers(new Array(quizQuestions.length).fill(null));
                }}
                className="bg-red-500 hover:bg-red-700 dark:bg-red-600 dark:hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition-colors"
              >
                Close
              </button>
            </div>
            {showResults && (
              <div className="mt-6 p-4 bg-gray-100 dark:bg-gray-800 rounded-lg">
                <h3 className="text-xl font-bold mb-2 dark:text-white">Quiz Results</h3>
                <p className="dark:text-white">
                  You got {score} out of {quizQuestions.length} questions correct! 
                  ({((score / quizQuestions.length) * 100).toFixed(1)}%)
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}