'use client';

import { InlineMath, BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';

export default function GlobalWarmingAndClimateChange() {
  return (
    <div className="px-6 py-10 max-w-4xl mx-auto text-justify">
      <h1 className="text-3xl font-bold mb-6">Global Warming and Climate Change</h1>

      <p>
        In this sub-section, we will discuss the role of several chemical reactions that occur in the atmosphere, as well as direct emissions of some greenhouse gases into the atmosphere which cause global warming. In general, the relationship between chemistry and climate change will be explored under two headings: global warming and climate change from the standpoint of chemistry, and greenhouse gas chemistry and its impacts on climate change.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Why Chemistry is so Important in the Fight Against Climate Change?</h2>
      <p>
        Any human activity has a definite impact on the environment. In this context, climate change is one of the main current concerns and challenges for mankind. Data in our hands reveals the existence of a global warming process, and urgent actions are needed before dramatic and irreversible (on a human scale) climate changes take place. The emission of certain substances to the atmosphere produces a greenhouse effect contributing to global warming. Even if their origin is diverse, many of these emitted gases or substances resulted from:
      </p>
      
      <p>
        Certain types of chemical reactions, mainly from the combustion of fuel:
      </p>
      <BlockMath>{`C_XH_Y + O_2 -> CO_2 + H_2O + \text{heat energy}`}</BlockMath>
      <p>Where X and Y represent the carbon and hydrogen numbers of the hydrocarbon compound.</p>

      <p>
        Some of them may be manufactured products like CFCs, solvents, and volatile organic compounds.
      </p>

      <p>
        Some have a natural origin, such as methane generated by living organisms, particularly in the oceans.
      </p>

      <p>
        In other cases, however, they are associated with human activities. The most well-known is carbon dioxide (CO₂), and its increasing content in the atmosphere is mainly associated with the combustion of fossil fuels.
      </p>

      <p>
        According to data from the US Department of Energy, global emissions of carbon dioxide resulting from the combustion of fossil fuels have increased by a factor of 10 since 1900. A variety of other gases contribute to the greenhouse effect, including solvents, chlorofluorocarbons, volatile organic compounds (VOCs), nitrogen, and sulfur oxides. Some of them can have, intrinsically, an even greater greenhouse effect than CO₂, but in general, they are released to the atmosphere in much smaller amounts. Besides, some of them, like nitrogen oxides, are generated concomitantly with CO₂ in combustion.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Greenhouse Effect</h2>
      <p>
        The greenhouse effect happens when certain gases, known as greenhouse gases, accumulate in Earth’s atmosphere. Greenhouse gases include carbon dioxide (CO₂), methane (CH₄), nitrous oxide (N₂O), ozone (O₃), water vapor (H₂O), and fluorinated gases. These gases warm our planet by absorbing infrared (IR) radiation that would otherwise escape into space. Without this warming effect, called the greenhouse effect, the average temperature on Earth would be a chilly 255 K (that’s -18°C, or the temperature on an extremely cold winter day). 
      </p>

      <p>
        Because these greenhouse gases in our atmosphere absorb IR light, Earth’s average temperature is 288 K (that’s 15°C, about the temperature on a slightly cool spring day). Thus, Earth is 33 K warmer than what would be expected if there were no greenhouse effect.
      </p>

      <p>
        For example, CO₂ (g) and H₂O (g) do absorb IR light and, upon doing so, gain energy which is transferred to the rest of the Earth. Even though these gases are present in small amounts, they are very good at absorbing infrared light. Thus, these atmospheric gases are the main contributors to the greenhouse effect.
      </p>

      <p>
        On the other hand, both N₂ (g) and O₂ (g) are present in very large amounts in the atmosphere, but these gases do not absorb IR light and therefore do not contribute to the greenhouse effect.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Contribution of Greenhouse Gases to Global Warming</h2>
      <p>
        Not all greenhouse gases produced by human activities have the same effect, nor do they come from the same sources. Each lasts for a different time in the atmosphere. Here are the five gases of human origin that contribute most to global warming:
      </p>

      <table className="table-auto border-collapse border border-gray-300 w-full mt-6">
        <thead>
          <tr>
            <th className="border border-gray-300 px-4 py-2">Greenhouse Gas</th>
            <th className="border border-gray-300 px-4 py-2">Sources of Emission</th>
            <th className="border border-gray-300 px-4 py-2">Time Spent in Atmosphere</th>
            <th className="border border-gray-300 px-4 py-2">Contribution to Global Warming</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="border border-gray-300 px-4 py-2">Carbon Dioxide (CO₂)</td>
            <td className="border border-gray-300 px-4 py-2">Processes like fuel use, deforestation, and cement production</td>
            <td className="border border-gray-300 px-4 py-2">80% lasts for 200 years, the other 20% can last up to 30,000 years</td>
            <td className="border border-gray-300 px-4 py-2">52.92%</td>
          </tr>
          <tr>
            <td className="border border-gray-300 px-4 py-2">Methane (CH₄)</td>
            <td className="border border-gray-300 px-4 py-2">Livestock production, agriculture, sewage treatment, oil and gas distribution, coal mining, fuel use</td>
            <td className="border border-gray-300 px-4 py-2">Lasts an average of 12 years</td>
            <td className="border border-gray-300 px-4 py-2">14.88%</td>
          </tr>
          <tr>
            <td className="border border-gray-300 px-4 py-2">Halogenated Compounds (CFCs, HCFCs)</td>
            <td className="border border-gray-300 px-4 py-2">Chemical production in refrigeration, air conditioning, electronics, etc.</td>
            <td className="border border-gray-300 px-4 py-2">Varies from months to tens of thousands of years</td>
            <td className="border border-gray-300 px-4 py-2">10.78%</td>
          </tr>
          <tr>
            <td className="border border-gray-300 px-4 py-2">Tropospheric Ozone (O₃)</td>
            <td className="border border-gray-300 px-4 py-2">Generated by combustion of carbon monoxide, nitrogen dioxide, and VOCs</td>
            <td className="border border-gray-300 px-4 py-2">Lasts for months</td>
            <td className="border border-gray-300 px-4 py-2">10.72%</td>
          </tr>
          <tr>
            <td className="border border-gray-300 px-4 py-2">Nitrous Oxide (N₂O)</td>
            <td className="border border-gray-300 px-4 py-2">Use of fertilizers, fuel, chemical production, and sewage treatment</td>
            <td className="border border-gray-300 px-4 py-2">Up to 114 years</td>
            <td className="border border-gray-300 px-4 py-2">10.70%</td>
          </tr>
        </tbody>
      </table>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Green Chemistry and Cleaner Production</h2>
      <p>
        Green chemistry is an area of chemistry that seeks to design chemical products and processes that minimize the use and generation of hazardous substances. By promoting cleaner production, we can reduce the impact of human activities on the environment and help mitigate climate change.
      </p>
    </div>
  );
}
