"use client"

import { InlineMath, BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';

export default function MagneticFieldLines() {
  return (
    <div className="px-6 sm:px-6 py-10 max-w-4xl mx-auto text-justify">
      <h1 className="text-3xl font-bold mb-6">4.2 Magnetic Field Lines</h1>

      <p>
        Magnetic field lines are imaginary lines or a visual tool used to represent magnetic fields. The density of the lines
        indicates the magnitude of the field. As with electric fields, the pictorial representation of magnetic field lines is
        very useful for visualizing the strength and direction of the magnetic field. When iron filings are sprinkled around a
        magnet, they orient themselves along the magnetic field lines, forming a magnetic field pattern around the magnet.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Properties of Magnetic Field Lines</h2>
      <ul className="list-disc ml-6 mb-6">
        <li>
          Field lines have both direction and magnitude at any point on the field. The direction of the magnetic field is tangent
          to the field line at any point in space. A small compass placed in a magnetic field will point in the direction of the
          field line.
        </li>
        <li>
          The strength of the field is proportional to the closeness of the lines.
        </li>
        <li>
          Magnetic field lines can never cross each other, meaning that the field is unique at any point in space.
        </li>
        <li>
          Unlike electric field lines, magnetic field lines are continuous, forming closed loops without beginning or end.
        </li>
        <li>
          The field lines emerge from the north pole and merge at the south pole. Inside the magnet, the direction of field lines is
          from its south pole to its north pole. Thus, the magnetic field lines are closed curves.
        </li>
      </ul>

      <p>
        The connection between electricity and magnetism has many important applications in today’s world. Whenever a current passes
        through a conductor, a magnetic field is produced. This is the basis of the electromagnet. This can be shown by placing a
        directional compass near a straight current-carrying wire or conductor. A compass placed near a current-carrying conductor
        will always point in the direction of the magnetic field lines produced. As soon as the current is turned off, there is no
        magnetic field. This is because the magnetic field is generated by the electric current (moving charges).
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Ampere’s Law</h2>
      <p>
        Ampere’s Law can be stated as: <InlineMath>{"B = \mu_0 I"}</InlineMath>, where the magnetic field (B) created by an electric
        current (I) is proportional to the size of that electric current, with a constant of proportionality equal to the
        permeability of free space (<InlineMath>{"\mu_0"}</InlineMath>).
      </p>
    </div>
  );
}
