'use client';

import { InlineMath, BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';

export default function Electromagnetism() {
  return (
    <div className="px-6 sm:px-6 py-10 max-w-4xl mx-auto text-justify">
      <h1 className="text-3xl font-bold mb-6">Unit 4: Electromagnetism</h1>

      <h2 className="text-2xl font-semibold mt-6 mb-4">4.1 Introduction</h2>
      <p>
        Electromagnetism is one of the fundamental forces of nature, consisting of the elements of electricity and
        magnetism. It involves the study of the electromagnetic force, which is carried by electromagnetic fields composed
        of electric fields and magnetic fields. At the subatomic level, electromagnetism governs the attraction and repulsion
        of electrically charged particles. For example, when electrically charged particles such as electrons are set in motion,
        they create a magnetic field. If these particles oscillate, they produce electromagnetic radiation, such as radio waves.
      </p>

      <p>
        Electricity and magnetism have been known to humanity for centuries. However, their relationship was discovered in 1819,
        when Hans Christian Oersted observed that an electric current in a wire deflected a nearby compass needle during a lecture
        demonstration. This experiment was the first reproducible observation of a connection between electricity and magnetism.
        Oersted found that a current-carrying wire produced a magnetic field, with the field's strength and direction dependent on
        the magnitude and direction of the current.
      </p>

      <p>
        In the 1820s, Michael Faraday and Joseph Henry independently demonstrated further connections between electricity and magnetism.
        They showed that an electric current could be induced in a circuit either by moving a magnet near the circuit or by varying the
        current in a nearby circuit. This discovery laid the foundation for the study of electromagnetic induction.
      </p>

      <p>
        The discovery of electromagnetism marked the birth of modern science and technology. It is now understood that all magnetic
        phenomena result from forces arising due to electric charges in motion. Without an understanding of electromagnetism, the
        invention of devices such as radios, televisions, computers, tape recorders, CD players, electric motors, and generators
        would not have been possible.
      </p>
      <h1 className="text-3xl font-bold mb-6">4.1 Magnets and Magnetic Field</h1>

      <p>
        A magnet generates a magnetic field, which represents the magnetic force existing in the region around the magnet.
        A magnetic pole is the part of a magnet that exerts the strongest force on other magnets or magnetic materials such
        as iron, nickel, and cobalt. Every magnet has two poles: a north pole (N) and a south pole (S). Like poles (N-N or S-S)
        repel each other, and opposite poles (N-S) attract each other.
      </p>

      <p>
        Although the force between two magnetic poles is similar to the force between two electric charges, electric charges
        can be isolated (as a positive and negative charge), whereas it is not possible to separate the north and south poles
        of a magnet. That is, magnetic poles are always found in pairs. No matter how many times a permanent magnet is cut into
        two, each piece always has a north and a south pole.
      </p>

      <p>
        Permanent and electromagnets are the two major types of materials that exhibit magnetic properties. Permanent magnets
        are materials where the magnetic field is generated by the internal structure of the material itself. Once permanent
        magnets are magnetized, they hold their magnetic property for a very long time.
      </p>

      <p>
        An electromagnet usually consists of wire wound into a coil. The electromagnet generates a magnetic field when an
        electric current is supplied to it, and it loses its magnetism when the current is turned off. Figure 4.2 shows a simple
        electromagnet consisting of a coil of wire wrapped around an iron core. The iron core serves to increase the strength of
        the magnetic field created.
      </p>

      <p>
        The Earth has a magnetic field. The magnetic field behaves like a giant bar magnet inside the Earth, with the North
        magnetic pole corresponding to the South Geographic Pole and vice versa. A compass needle aligns itself in a north-south
        direction to line up with Earth’s magnetic field.
      </p>

      <p>
        The magnetic field is the region around a magnet or a moving electric charge within which the force of magnetism acts.
        As you have learned in previous grades, an electric field surrounds an electric charge. Similarly, a magnetic field also
        surrounds a magnet. The magnetic field is a vector quantity, and the vector points in the direction that a compass would point.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Differences Between Electric Field and Magnetic Field</h2>
      <ul className="list-disc ml-6 mb-6">
        <li>
          The SI unit of an electric field is Newton per coulomb, whereas the SI unit of magnetic field is Tesla.
        </li>
        <li>
          The region around the electric charge where the electric force exists is called an electric field. The region around the
          magnet where the pole of the magnet exhibits a force of attraction or repulsion is called a magnetic field.
        </li>
        <li>
          The electric field is produced by a unit charge, i.e., either a positive or a negative charge, whereas the magnetic field
          is caused by a dipole of the magnet (i.e., the north and south poles).
        </li>
        <li>
          The electric field lines start on a positive charge and end on a negative charge, whereas the magnetic field lines do
          not have starting or ending points.
        </li>
        <li>
          The electric field lines do not form a loop, whereas the magnetic field lines form a closed loop.
        </li>
      </ul>
    </div>
  );
}